<#
.SYNOPSIS
  Write traccar-fleet-system/frontend/.env for Phase 1 (Dev PC -> NumzLab).

.PARAMETER NumzLabHost
  NumzLab LAN IP or hostname (no scheme), e.g. 192.168.1.50

.EXAMPLE
  .\scripts\setup-devpc-frontend-env.ps1 -NumzLabHost 192.168.1.50
#>
param(
  [Parameter(Mandatory = $true)]
  [string]$NumzLabHost
)

$ErrorActionPreference = 'Stop'
$RepoRoot = Split-Path -Parent $PSScriptRoot
$FrontendDir = Join-Path $RepoRoot 'traccar-fleet-system\frontend'
$OutPath = Join-Path $FrontendDir '.env'

$hostTrimmed = $NumzLabHost.Trim().TrimEnd('/')
if ($hostTrimmed -match '^https?://') {
  throw 'Pass host only (e.g. 192.168.1.50), not a full URL.'
}

$content = @"
# Generated by setup-devpc-frontend-env.ps1 — Phase 1 Dev PC -> NumzLab
# gitignored; safe to regenerate.

REMOTE_API_BASE_URL=http://${hostTrimmed}:8082
VITE_FUEL_API_URL=http://${hostTrimmed}:3000
VITE_DEV_SERVER_PORT=5174
VITE_HMR_EXTERNAL=
"@

Set-Content -LiteralPath $OutPath -Value $content -Encoding UTF8 -NoNewline
Add-Content -LiteralPath $OutPath -Value "`n" -Encoding UTF8

Write-Host "Wrote $OutPath" -ForegroundColor Green
Write-Host "  REMOTE_API_BASE_URL=http://${hostTrimmed}:8082"
Write-Host "  VITE_FUEL_API_URL=http://${hostTrimmed}:3000"
Write-Host ""
Write-Host "Next:" -ForegroundColor Cyan
Write-Host "  cd traccar-fleet-system\frontend"
Write-Host "  npm run dev"
Write-Host "  Open http://localhost:5174"
